-- AlterTable
ALTER TABLE "books" ALTER COLUMN "bookAuthor" DROP NOT NULL,
ALTER COLUMN "bookPublisher" DROP NOT NULL,
ALTER COLUMN "userId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "books" ADD CONSTRAINT "books_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
